### PR TITLE
docs: Enhance Security with GitHub Actions and Snyk Integration

### PR DESCRIPTION
**Pull request by keyrrperino**
## What does this PR do?
- Implements GitHub Actions and Snyk for automated security checks and CI/CD workflow enhancement

## Why did you choose this solution?
- To enhance project security and automate deployment processes

## What is the dependency graph of the changes?
- GitHub Actions setup files and workflow definitions
- Snyk configuration and vulnerability scan files

## How to test/verify?
- Review workflow results in GitHub Actions tab
- Check Snyk dashboard for vulnerability reports

## Related ticket url:
-

### CODE REVIEW

**Comment by symphdevtools** [comment]
Hi! I'm generating PR title and description for you and will automatically apply it to your PR. I'll react :rocket: to this comment when done. Just sit back and chill!

When you have new changes to this PR and you want to regenerate the title and PR description, just comment `churva`!

Let me know if something is not working well, e.g.:
- Some parts of the title and description weren't preserved when generating title and description
- Disappearing screenshots or links
- Etc.

Thanks!

(RIP hatdog)

**Comment by keyrrperino** [comment]
churva

**Review by JHNLWHD — CHANGES_REQUESTED** [review]
@keyrrperino link the files here: https://github.com/symphco/engineering-standards/blob/main/standards/cloud_defaults.md

**Comment by keyrrperino** [comment]
update the pr @JHNLWHD.

**Review by JHNLWHD — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
